### ISSUE TITLE
How to improve the build process?

### ISSUE THREAD

**Issue by techeverri** [nicolasepiscopo/name-that-color-less-sass#2]
Hi @nicolasepiscopo,

I want to know how to build the extension to a CRX file manually. Considering you need to pre-compile Less files before, it would be great to automate production code generation.

I want to help and learn a lot contributing to your project.

Regards

**Comment by nicolasepiscopo** [comment]
Hey @techeverri ,

It’s not really needed to make a crx extension. Google allow us upload zip files. Is simple as compress all the Project to a zip file.

Surely we can do this automated with webpack, grunt or gulp in order to include production only files.

I was thinking about changing to React, in that way I’d preffer to use webpack. What do you think about it?

Regards

**Comment by techeverri** [comment]
Changing to React would be great including all the tooling (webpack, babel, npm, etc) and features (ES2015, JSX, etc).

Let's do it!

**Comment by nicolasepiscopo** [comment]
Please take a look at this branch https://github.com/nicolasepiscopo/name-that-color-less-sass/tree/webpack-react

We can work on there, there's a lot of work to be done. I've set up the environment to make react work with live reloads but build and sass config aren't working.

**Comment by techeverri** [comment]
I was thinking more like doing baby steps, based on the current stable (fully functional) version. Every little change would add new features but keep app running as functional as today.

**Comment by nicolasepiscopo** [comment]
Nowadays in **webpack-react** branch there's a folder named old-app which maintains the previous code, so it's still functional here and in master. We can work in **webpack-react** branch till we have an stable version with automated packaging and the app transported to React. 

If you want you can take part on the automated packaging task and I can continue changing the app to work with React. I'll make the tasks, please assign the automated zipping related one to you (because I can't do it.. I don't know why).

BTW I've made an Slack team to discuss this sort of things, could you please give me your email address? so I can invite you.

**Comment by techeverri** [comment]
You need to add me as a collaborator in order to appear as assignee.
`/settings -> /collaboration`

I'll send you my email address via ~~Twitter~~ LinkedIn

**Comment by nicolasepiscopo** [comment]
Done

**Comment by nicolasepiscopo** [comment]
Opened issue #3 refering to this question. Closing this issue.
